const moviesDB = [
    {
        id: 0, 
        title: "El Viaje de Chihiro",
        category: ["Anime", "Aventura", "Pelicula"],
        type: "Pelicula",
        rating: 4.9,
        img: "https://images.justwatch.com/poster/243968442/s718/el-viaje-de-chihiro.jpg",
        description: "Chihiro es una niña de diez años que viaja en coche con sus padres. Después de atravesar un túnel, llegan a un mundo fantástico...",
        trailer: "https://youtu.be/5Fgq4Osh6XQ",
        year: "2001",
        director: "Hayao Miyazaki"
    },
    {
        id: 1,
        title: "Titanic",
        category: ["Romance", "Drama", "Pelicula"],
        type: "Pelicula",
        rating: 4.7,
        img: "https://m.media-amazon.com/images/M/MV5BNjQ4NGU5ZWEtMjM1My00MTcxLWIzYWMtN2MwM2E2MWYzODk2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        description: "Una joven de la alta sociedad abandona a su arrogante pretendiente por un artista humilde en el trasatlántico que se hundió durante su viaje inaugural.",
        trailer: "https://youtu.be/wMZuro21wtE?si=3fevZmy_H8BBsZnl", // Puedes llenar esto poco a poco
        year: "1997",
        director: "James Cameron"
    },
    {
        id: 2,
        title: "The Boys",
        category: ["Acción", "Comedia", "Serie"],
        type: "Serie",
        rating: 4.8,
        img: "https://m.media-amazon.com/images/M/MV5BMWJlN2U5MzItNjU4My00NTM2LWFjOWUtOWFiNjg3ZTMxZDY1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        description: "La serie está ambientada en un mundo donde los superhéroes, conocidos como Supers son tratados como celebridades, pero la mayoría están corrompidos por la fama y el poder. Estos héroes trabajan para Vought International, una corporación multimillonaria que comercializa sus imágenes y oculta sus crímenes más oscuros.",
        trailer: "https://youtu.be/8-PTZXcmdOA?si=1d0pZ12JN9Hg-krj", // Puedes llenar esto poco a poco
        year: "2019",
        director: "Philip Sgriccia"
    },
    {
        id: 3,
        title: "Matrix", 
        category: ["Sci-Fi", "Acción", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.9, 
        img: "https://pics.filmaffinity.com/Matrix-430409153-large.jpg",
        description: "Thomas Anderson es un programador que descubre que su mundo es una realidad virtual creada por máquinas para esclavizar a la humanidad. Tras unirse a un grupo de rebeldes, debe aprender a dominar sus habilidades en ese entorno digital para combatir a los programas que lo protegen y liderar la liberación de la raza humana.",
        trailer: "https://youtu.be/OM0tSTEQCQA?si=QAchSkQdUjioZGvh", // Puedes llenar esto poco a poco
        year: "1999",
        director: "Hermanas Wachowski"
    },
    {
        id: 4,
        title: "El Conjuro", 
        category: ["Terror", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.5, 
        img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEil91uWcWktClfvIvmV6qtU11ZipAlkALkCOXzyuqv0XH8vNgmE_YErlx8nKvxP2nO6VWaJOw8Rgvgwm6XjILiH2jrbY6tZAG3QCrI8eYOwoUVOKYxXRPdRAV82UOmAx9R9nOwalinXt0Dg/s1600/the-conjuring-poster.jpg",
        description: "Basada en un caso real, la trama sigue a los investigadores de lo paranormal Ed y Lorraine Warren. Ambos acuden a una granja aislada donde una familia es aterrorizada por una presencia oscura. Al enfrentarse a una poderosa entidad demoníaca, los Warren se ven envueltos en el caso más aterrador de sus carreras.",
        trailer: "https://youtu.be/_zU1gLWGnpg?si=01_LCEqovrYqaFOM", // Puedes llenar esto poco a poco
        year: "2013",
        director: "James Wan"
    },
    {
        id: 5,
        title: "Todo a la vez en todas partes", 
        category: ["Sci-Fi", "Aventura", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.8, 
        img: "https://upload.wikimedia.org/wikipedia/en/1/1e/Everything_Everywhere_All_at_Once.jpg", 
        description: "Evelyn es una inmigrante china agotada por su vida y sus deudas fiscales que descubre la existencia del multiverso. Para salvar la existencia de una amenaza oscura, debe conectar con las versiones de sí misma en otros universos y canalizar sus habilidades. La aventura se convierte en un viaje emocional donde debe reparar sus relaciones familiares mientras lucha en mundos extraños.",
        trailer: "https://youtu.be/U3cKYWgl2dU?si=uG_4dTgCcZVa-XF6", // Puedes llenar esto poco a poco
        year: "2022",
        director: "Daniel Kwan y Daniel Scheinert"
    },
    {
        id: 6,
        title: "Goblin", 
        category: ["Romance", "Fantasia", "Serie"], 
        type: "Serie", 
        rating: 4.9, 
        img: "https://images.justwatch.com/poster/185481575/s718/goblin-el-solitario-ser-inmortal.jpg", 
        description: "Kim Shin es un guerrero de la era Goryeo que es traicionado y condenado a la inmortalidad como un duende. Tras vivir 900 años viendo morir a sus seres queridos, la única forma de terminar con su castigo es encontrar a la Novia del Ser Inmortal, quien es la única capaz de extraer la espada invisible de su pecho. Su destino se cruza con una estudiante que puede ver fantasmas y con un Ángel de la Muerte con amnesia.",
        trailer: "https://youtu.be/S94ukM8C17A?si=v01JOoSoUKe1tChj", // Puedes llenar esto poco a poco
        year: "2016",
        director: "Lee Eung Bok"
    },
    {
        id: 7,
        title: "The Office", 
        category: ["Comedia", "Serie"], 
        type: "Serie", 
        rating: 4.7, 
        img: "https://upload.wikimedia.org/wikipedia/en/5/58/TheOffice_S7_DVD.jpg", 
        description: "Bajo el formato de falso documental, la serie sigue el día a día de los empleados de Dunder Mifflin, una empresa papelera en Scranton. La trama gira en torno a Michael Scott, un jefe inepto y desesperado por ser querido, y las dinámicas, bromas y romances que surgen entre sus peculiares trabajadores mientras intentan sobrevivir a la monotonía de la oficina.",
        trailer: "https://youtu.be/-C2z-nshFts?si=ol77mhYPvpPLxqjM", // Puedes llenar esto poco a poco
        year: "2005",
        director: "Greg Daniels (Creador), Ken Kwapis, Paul Feig"
    },
    {
        id: 8,
        title: "Pájaros de Verano", 
        category: ["Drama", "Crimen", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.6, 
        img: "https://m.media-amazon.com/images/M/MV5BMmU4ODRkOGItNjJkNi00ZTRlLWFmZGQtZDE0ODljZTEzOWE3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
        description: "La historia narra el ascenso y la caída de una familia Wayúu durante la época de la bonanza marimbera en la Guajira. Lo que comienza como un próspero negocio de venta de marihuana a extranjeros termina desatando una guerra fratricida que destruye su cultura y sus tradiciones ancestrales. La codicia y el honor se enfrentan en una tragedia épica que cambia para siempre la historia de la región.",
        trailer: "https://youtu.be/oZTDbNEAAQM?si=xpu2ltk7E3c_npKn", // Puedes llenar esto poco a poco
        year: "2018",
        director: "Ciro Guerra y Cristina Gallego"
    },
    {
        id: 9,
        title: "Coco", 
        category: ["Familia", "Comedia", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.9, 
        img: "https://lumiere-a.akamaihd.net/v1/images/p_coco_19736_fd5fa537.jpeg", 
        description: "Miguel es un niño que sueña con ser músico, pero su familia se lo prohíbe debido a un antiguo trauma del pasado. Durante la celebración del Día de Muertos, Miguel queda atrapado mágicamente en el Mundo de los Muertos tras intentar tomar prestada la guitarra de su ídolo. Allí emprende una colorida aventura junto a un astuto esqueleto llamado Héctor para encontrar a sus ancestros, recibir su bendición y descubrir la verdadera historia de su familia antes de quedar atrapado para siempre.",
        trailer: "https://youtu.be/awzWdtCezDo?si=grGif_CdgX3Xx2pn", // Puedes llenar esto poco a poco
        year: "2017",
        director: "Lee Unkrich y Adrián Molina"
    },
    {
        id: 10,
        title: "Demon Slayer: Mugen Train", 
        category: ["Anime", "Acción", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.8, 
        img: "https://m.media-amazon.com/images/M/MV5BNzEzYjhkYTctMWNmZS00MTc5LWI4OWUtZjFkNzNkYTNkMTJlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
        description: "Tanjiro y sus compañeros se unen a Kyojuro Rengoku, el Pilar de la Llama, para investigar una serie de desapariciones dentro de un tren. Allí caen bajo el hechizo de un demonio que manipula los sueños para destruir su voluntad. Tras despertar y librar una feroz batalla para salvar a los pasajeros, deben enfrentarse a una amenaza mucho mayor que pondrá a prueba el honor y el sacrificio de los cazadores de demonios.",
        trailer: "https://youtu.be/-AwLMRgcEoA?si=dtA4pFdCKjA3V6uK", // Puedes llenar esto poco a poco
        year: "2020",
        director: "Haruo Sotozaki"
    },
    {
        id: 11,
        title: "Kingsman", 
        category: ["Acción", "Comedia", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.5, 
        img: "https://pics.filmaffinity.com/Kingsman_Servicio_secreto-485444831-large.jpg" , 
        description: "Eggsy es un joven brillante pero problemático que vive en un barrio humilde de Londres. Su vida cambia cuando Harry Hart, un refinado espía de una organización ultrasecreta, lo recluta para un programa de entrenamiento extremadamente competitivo. Mientras Eggsy intenta superar las pruebas para convertirse en un nuevo agente, debe ayudar a detener a un genio tecnológico que planea eliminar a gran parte de la población mundial mediante un chip telefónico",
        trailer: "https://youtu.be/Rs5J8kh62yo?si=CgpUC4hI2BjJR3nN",
        year: "2014",
        director: "Matthew Vaughn"
    },
    {
        id: 12,
        title: "Five Nights at Freddy's", 
        category: ["Terror", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.2, 
        img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSVPivSEOPVmHn_Egmig4GtQdvv4pQiSXqO6_p9D_CyvH63jtoD" , 
        description: "Mike es un joven con problemas que acepta un trabajo como guardia de seguridad nocturno en Freddy Fazbear's Pizza, un centro de entretenimiento familiar abandonado desde los años 80. Pronto descubre que los cuatro animatrónicos del lugar cobran vida por la noche y matan a cualquier intruso. Mike debe sobrevivir a sus turnos mientras intenta proteger a su hermana pequeña y descubrir la verdad sobre la desaparición de unos niños en el local.",
        trailer: "https://youtu.be/FRffQncR1HQ?si=LLICjgUHT-a9qI-z",
        year: "2023",
        director: "Emma Tammi"
    },
    {
        id: 13,
        title: "Scream", 
        category: ["Terror", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.6, 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9FNzMEVM-F1HSDV2PUfnvtQRrp-L5yDD0Z8mad1e-xtzElZctT-hoq9-TbqXwdpMSTTKfjvWQodQgNHSBgDSvXlVmZBZV3j3Kx7OkQQo&s=10" , 
        description: "Un año después del asesinato de su madre, Sidney Prescott y sus amigos comienzan a recibir llamadas amenazantes de un asesino enmascarado conocido como Ghostface. El criminal utiliza trivias de películas de terror para aterrorizar a sus víctimas antes de matarlas. Mientras el pueblo de Woodsboro entra en pánico y las reglas del cine de horror parecen volverse realidad, Sidney debe descubrir quién se esconde tras la máscara antes de convertirse en la siguiente víctima.",
        trailer: "https://youtu.be/Zt3bqsMcz9g?si=iaNGYSAU4pB1799w",
        year: "1996",
        director: "Wes Craven"
    },
    {
        id: 14,
        title: "Bridgerton", 
        category: ["Romance", "Drama", "Serie"], 
        type: "Serie", 
        rating: 4.3, 
        img: "https://m.media-amazon.com/images/M/MV5BYzc4NmIwNGMtNGIzNy00Nzg2LWFlNzItYzhmNjQ1NGUwNTg1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
        description: "En el Londres de la época de la Regencia, ocho hermanos de la poderosa familia Bridgerton buscan el amor y la felicidad en la alta sociedad. La trama se centra en los bailes, los escándalos y las presiones sociales, todo mientras una misteriosa escritora anónima, Lady Whistledown, publica los secretos más íntimos de la élite en su pasquín, poniendo en riesgo la reputación de todos los que buscan un buen matrimonio.",
        trailer: "https://youtu.be/AdBweWvuG68?si=4DHcbbC9VBgjs6Zg",
        year: "2020",
        director: "Chris Van Dusen"
    },
    {
        id: 15,
        title: "Avengers: Endgame", 
        category: ["Acción", "Sci-Fi", "Pelicula"], 
        type: "Pelicula", 
        rating: 5.0, 
        img: "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_.jpg", 
        description: "Tras el devastador chasquido de Thanos que eliminó a la mitad de la vida en el universo, los Vengadores restantes se encuentran derrotados y dispersos. Cinco años después, surge una oportunidad desesperada para viajar a través del tiempo y recuperar las Gemas del Infinito antes de que Thanos las obtenga. El equipo debe reunirse una última vez para intentar revertir el daño y restaurar el orden en el cosmos, sin importar las consecuencias o los sacrificios necesarios.",
        trailer: "https://youtu.be/svLSGZkTzC0?si=V_dCHTQ5kvp_5qiB",
        year: "2019",
        director: "Anthony Russo y Joe Russo"
    },
    {
        id: 16,
        title: "Breaking Bad", 
        category: ["Drama", "Crimen", "Serie"], 
        type: "Serie", 
        rating: 4.9, 
        img: "https://m.media-amazon.com/images/M/MV5BMzU5ZGYzNmQtMTdhYy00OGRiLTg0NmQtYjVjNzliZTg1ZGE4XkEyXkFqcGc@._V1_QL75_UX190_CR0,2,190,281_.jpg" , 
        description: "Walter White es un frustrado profesor de química de secundaria que es diagnosticado con cáncer de pulmón inoperable. Para asegurar el futuro financiero de su familia antes de morir, decide usar sus conocimientos para cocinar metanfetamina de alta pureza junto a un antiguo alumno, Jesse Pinkman. Lo que comienza como un plan desesperado lo arrastra a una violenta transformación personal y a un peligroso descenso en el mundo del narcotráfico.",
        trailer: "https://youtu.be/HhesaQXLuRY?si=_lG4UvJH3isvaTEN",
        year: "2008",
        director: "Vince Gilligan"
    },
    {
        id: 17,
        title: "Juraccic World: Renace", 
        category: ["Acción", "Sci-Fi", "Pelicula"], 
        type: "Pelicula", 
        rating: 3.5, 
        img: "https://m.media-amazon.com/images/M/MV5BMGM3ZmI3NzQtNzU5Yi00ZWI1LTg3YTAtNmNmNWIyMWFjZTBkXkEyXkFqcGc@._V1_.jpg" , 
        description: "Cinco años después de que los dinosaurios se dispersaran por el mundo, la ecología del planeta se ha vuelto hostil para ellos y los pocos supervivientes viven en zonas ecuatoriales aisladas. Una experta en operaciones encubiertas es enviada a una misión secreta para obtener ADN de las tres criaturas más colosales de esa biosfera, las cuales poseen la clave para un fármaco milagroso. Sin embargo, tras naufragar en una isla prohibida, su equipo y una familia de civiles descubren un secreto siniestro que ha estado oculto por décadas.",
        trailer: "https://youtu.be/1R3LTANp7hw?si=8IZEx5d5WvVKo5qn",
        year: "2025",
        director: "Gareth Edwards"
    },
    {
        id: 18,
        title: "An Unexpected Christmas", 
        category: ["Comedia", "Romance", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.7, 
        img: "https://m.media-amazon.com/images/M/MV5BZGRmMjM5NGMtYmM4NC00N2M4LThjZGMtMzRiMjM1ODk0MDk1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
        description: "Jamie decide no contarle a su familia que acaba de romper con su novia Emily justo antes de Navidad. Cuando se encuentran por accidente en la estación de tren, él la convence para que finja que siguen juntos durante las fiestas para no arruinar el ánimo familiar. Mientras participan en las tradiciones locales y eventos navideños, ambos empiezan a recordar por qué se enamoraron y deben decidir si su relación merece una segunda oportunidad real.",
        trailer: "https://youtu.be/soVeiBupn3k",
        year: "2021",
        director: "Michael Robison"
    },
    {
        id: 19,
        title: "Five Nights at Freddy’s 2", 
        category: ["Terror", "Pelicula"], 
        type: "Pelicula", 
        rating: 2.3, 
        img: "https://preview.redd.it/new-poster-for-five-nights-at-freddys-2-v0-wq7s0e5gsduf1.jpeg?auto=webp&s=61c93fdc66224baa2b7df20acd34494f8240f989", 
        description: "La historia continúa tras los eventos de la primera entrega, siguiendo nuevamente a Mike Schmidt mientras se adentra más en los oscuros secretos de Freddy Fazbear's Pizza. En esta ocasión, la trama introduce a los modelos 'Toy', versiones aparentemente más amigables pero igualmente peligrosas de los animatrónicos originales. Mike deberá sobrevivir a nuevas noches de terror mientras se enfrenta a revelaciones sobre el pasado de William Afton y el destino de las almas atrapadas en las máquinas.",
        trailer: "https://youtu.be/E8M-iJ0p-Xk?si=8yfpai-mGeY9lUj-",
        year: "2025",
        director: "Emma Tammi"
    },
    {
        id: 20,
        title: "Hot Fuzz (Super Policías)", 
        category: ["Comedia", "Acción", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.3, 
        img: "https://m.media-amazon.com/images/M/MV5BYjFkZTkzZTQtNjM1ZS00M2EyLWE3MTAtMmY5Yzk0NTc0NDc3XkEyXkFqcGc@._V1_.jpg" , 
        description: "Nicholas Angel es el mejor policía de Londres, tan eficiente que hace quedar mal a sus colegas, por lo que es transferido al tranquilo y aburrido pueblo de Sandford. Allí es asignado como compañero de Danny Butterman, un agente torpe y fanático de las películas de acción. Aunque el pueblo parece idílico, una serie de 'accidentes' espantosos llevan a Angel a sospechar que hay una conspiración oscura detrás de la paz perfecta de Sandford.",
        trailer: "https://youtu.be/L6PKkxn7pq0?si=LZZi3dahF_CJpj7V",
        year: "2007",
        director: "Edgar Wright"
    },
    {
        id: 21,
        title: "The Shawshank Redemption", 
        category: ["Drama", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.9, 
        img: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781668084984/the-shawshank-redemption-9781668084984_lg.jpg" , 
        description: "Andy Dufresne es un banquero condenado a cadena perpetua por un doble asesinato que afirma no haber cometido. En la dura prisión de Shawshank, entabla una profunda amistad con Red, un convicto veterano. A lo largo de los años, Andy utiliza su inteligencia y sus conocimientos financieros para ganarse el respeto de los guardias y mejorar la vida de sus compañeros, mientras mantiene viva la esperanza de recuperar su libertad de una forma que nadie imagina.",
        trailer: "https://youtu.be/NmzuHjWmXOc?si=prJLkC8MBK6A-8L4",
        year: "1994",
        director: "Frank Darabont"
    },
    {
        id: 22,
        title: "El Padrino", 
        category: ["Drama", "Crimen", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.4, 
        img: "https://pics.filmaffinity.com/El_padrino-590289523-large.jpg", 
        description: "Don Vito Corleone es el respetado y temido jefe de una de las cinco familias de la mafia en Nueva York. Cuando el capo se niega a entrar en el negocio del narcotráfico, se desata una violenta guerra entre clanes que pone en peligro a su familia. Su hijo menor, Michael, un héroe de guerra que siempre quiso mantenerse al margen de los negocios ilícitos, se ve obligado a intervenir y termina transformándose en el nuevo y despiadado heredero del imperio criminal.",
        trailer: "https://youtu.be/5GgH2QRzy_A?si=J479tc8XntI_v4pR",
        year: "1972",
        director: "Francis Ford Coppola"
    },
    {
        id: 23,
        title: "María, llena eres de gracia", 
        category: ["Drama", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.9, 
        img: "https://m.media-amazon.com/images/M/MV5BYzc2MjFhNDMtNTY2Ny00ZWQ5LWIxZmEtZjY4MjAxYThmMTdiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", 
        description: "María es una joven de 17 años que vive en un pequeño pueblo de Colombia y trabaja en una plantación de flores. Tras quedar embarazada y renunciar a su empleo por las malas condiciones, acepta una oferta peligrosa para ayudar económicamente a su familia: convertirse en 'mula' para transportar heroína hacia Estados Unidos dentro de su estómago. La película narra su angustiante viaje y la desesperada lucha por sobrevivir en un mundo donde su vida no tiene valor para quienes la contrataron.",
        trailer: "https://youtu.be/QDFvVfWmNtc?si=S1ezAvcf_SKBT74z",
        year: "2004",
        director: "Joshua Marston"
    },
    {
        id: 24,
        title: "Parque Jurásico", 
        category: ["Sci-Fi", "Aventura", "Pelicula"], 
        type: "Pelicula", 
        rating: 5.0, 
        img: "https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg", 
        description: "El multimillonario John Hammond logra cumplir su sueño de clonar dinosaurios mediante ingeniería genética y crear un parque temático en la Isla Nublar. Antes de abrirlo al público, invita a un grupo de científicos y a sus dos nietos para que avalen la seguridad del lugar. Sin embargo, tras un sabotaje en el sistema eléctrico, las feroces criaturas escapan de sus recintos, obligando a los supervivientes a luchar por sus vidas en una isla donde el hombre ya no es el depredador alfa.",
        trailer: "https://youtu.be/dLDkNge_AhE?si=Lwv0C4qBzVvO0mE8",
        year: "1993",
        director: "Steven Spielberg"
    },
    {
        id: 25,
        title: "Interstellar", 
        category: ["Sci-Fi", "Acción", "Pelicula"], 
        type: "Pelicula", 
        rating: 5.0, 
        img: "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_.jpg", 
        description: "En un futuro cercano donde la Tierra se está volviendo inhabitable debido a plagas agrícolas y tormentas de polvo, la supervivencia de la humanidad pende de un hilo. Joseph Cooper, un ex-piloto de la NASA convertido en granjero, es reclutado para una misión desesperada: viajar a través de un agujero de gusano recién descubierto cerca de Saturno. El objetivo es encontrar un nuevo hogar para la especie humana en otra galaxia, enfrentándose a la dilatación del tiempo, la soledad extrema y la inmensidad del espacio, mientras intenta cumplir la promesa de volver con sus hijos.",
        trailer: "https://youtu.be/UoSSbmD9vqc?si=q-gtqCzMcAK0L5HJ",
        year: "2014",
        director: "Christopher Nolan"
    },
    {
        id: 26,
        title: "Inception (El Origen)", 
        category: ["Sci-Fi", "Acción", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.7, 
        img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_FMjpg_UX1000_.jpg", 
        description: "Dom Cobb es un 'extractor', un ladrón experto en el arte de meterse en los sueños de los demás para robar secretos del subconsciente. Debido a su historial, es un fugitivo internacional, pero se le ofrece una oportunidad para recuperar su vida: realizar una 'incepción'. En lugar de robar una idea, debe implantar una en la mente de un poderoso heredero. Para lograrlo, él y su equipo deberán navegar por múltiples niveles de sueños dentro de sueños, enfrentándose a los peligros de la mente y a las proyecciones del propio pasado de Cobb.",
        trailer: "https://youtu.be/RV9L7ui9Cn8?si=DBJ0tA_rHvx6gTsi",
        year: "2010",
        director: "Christopher Nolan"
    },
    {
        id: 27,
        title: "Forrest Gump", 
        category: ["Drama", "Romance", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.8, 
        img: "https://images.justwatch.com/poster/167978449/s718/forrest-gump.jpg" , 
        description: "Forrest Gump es un hombre nativo de Alabama con una leve discapacidad intelectual y una bondad infinita. A pesar de sus limitaciones, su vida se convierte en una serie de eventos extraordinarios que lo llevan a participar en los momentos más importantes de la historia de Estados Unidos entre los años 50 y 80: desde enseñar a bailar a Elvis Presley y luchar en la guerra de Vietnam, hasta conocer a varios presidentes y fundar una empresa multimillonaria. A través de todo, Forrest nunca olvida a su único y gran amor, Jenny, cuya vida sigue un camino mucho más turbulento que el suyo.",
        trailer: "https://youtu.be/bLvqoHBptjg?si=-ZWLO7zFM2mOPNR_",
        year: "1994",
        director: "Robert Zemeckis"
    },
    {
        id: 28,
        title: "Your Name", 
        category: ["Anime", "Romance", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.2, 
        img: "https://m.media-amazon.com/images/M/MV5BMTIyNzFjNzItZmQ1MC00NzhjLThmMzYtZjRhN2Y3MmM2OGQyXkEyXkFqcGc@._V1_.jpg", 
        description: "Mitsuha es una chica de pueblo que anhela la vida de la ciudad, mientras que Taki es un joven estudiante en Tokio. Un día, descubren que, mientras duermen, sus cuerpos se intercambian de manera aleatoria. Comienzan a comunicarse dejando notas y reglas para no arruinar la vida del otro. Sin embargo, cuando intentan encontrarse en persona, descubren que una conexión mucho más profunda y un evento astronómico del pasado los une a través del tiempo y el espacio, obligándolos a luchar para evitar una tragedia.",
        trailer: "https://youtu.be/N0nvoAv5q8M?si=IiWHIqLNrflbN45B",
        year: "2016",
        director: "Makoto Shinkai"
    },
    {
        id: 29,
        title: "Akira", 
        category: ["Anime", "Sci-Fi", "Pelicula"], 
        type: "Pelicula", 
        rating: 5.0, 
        img: "https://pics.filmaffinity.com/akira-262742931-large.jpg", 
        description: "En el año 2019, la ciudad de Neo-Tokio está al borde del colapso, plagada de corrupción, protestas y violencia de bandas. Kaneda es el líder de una pandilla de motociclistas cuyo mejor amigo, Tetsuo, sufre un accidente tras encontrarse con un extraño niño con poderes psíquicos. El gobierno secuestra a Tetsuo para utilizarlo en un experimento secreto llamado 'Akira'. Pronto, Tetsuo comienza a desarrollar poderes telequinéticos incontrolables que amenazan con destruir la ciudad entera, mientras Kaneda intenta rescatarlo antes de que el caos sea absoluto.",
        trailer: "https://youtu.be/4I3C5Q19eDM?si=27hIUz1NCQF7otqe",
        year: "1988",
        director: "Katsuhiro Otomo"
    },
    {
        id: 30,
        title: "La Princesa Mononoke", 
        category: ["Anime", "Aventura", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.9, 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM_D9w0cW8mDvWt_2JwJWhRIyek0jKZHJfHA&s", 
        description: "La historia sigue a Ashitaka, el último príncipe de una tribu moribunda, quien es maldecido por un jabalí corrompido por el odio. En su búsqueda de una cura, llega a una región en guerra donde Lady Eboshi y los habitantes de la Ciudad del Hierro talan los bosques para progresar, enfrentándose a los dioses animales. Allí conoce a San, una joven humana criada por lobos (la 'Princesa Mononoke'), que odia a la humanidad. Ashitaka intentará encontrar una forma de que los humanos y la naturaleza coexistan sin destruirse mutuamente.",
        trailer: "https://youtu.be/bfZL9YpObw8?si=saQyQ6R7MRsehZco",
        year: "1997",
        director: "Hayao Miyazaki"
    },
    {
        id: 31,
        title: "A Silent Voice", 
        category: ["Anime", "Drama", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.8, 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6JvxT1_dQKD3QZmpSgP0DyL8iIlEjSy8vjw&s" , 
        description: "La historia gira en torno a Shoya Ishida, un chico que en primaria lideró el acoso escolar contra Shoko Nishimiya, una nueva compañera de clase sorda. Debido al bullying, Shoko termina cambiándose de escuela y Shoya es señalado como el único culpable, convirtiéndose él mismo en el blanco del acoso y aislándose del mundo. Años más tarde, atormentado por la culpa y habiendo aprendido lenguaje de señas, Shoya decide buscar a Shoko para pedirle perdón y tratar de reparar el daño causado, iniciando un difícil camino hacia la redención y la aceptación personal.",
        trailer: "https://youtu.be/zrnQYUBNam0?si=ZOtIrmOk-vplYdA_",
        year: "2016",
        director: "Naoko Yamada"
    },
    {
        id: 32,
        title: "El abrazo de la serpiente", 
        category: ["Drama", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.8, 
        img: "https://www.proimagenescolombia.com/photos/57150_3219__imagen__.jpg", 
        description: "La película narra dos historias que ocurren con 30 años de diferencia, ambas protagonizadas por Karamakate, un chamán amazónico y último sobreviviente de su pueblo: En 1909, Karamakate acompaña al científico alemán Theodor Koch-Grünberg, quien busca desesperadamente una planta sagrada y curativa llamada yakruna y En 1940, un Karamakate ya anciano y que ha olvidado sus tradiciones guía al biólogo estadounidense Richard Evans Schultes en la búsqueda de la misma planta. A través de estos viajes por el río Amazonas, la película explora el choque entre la sabiduría indígena y el colonialismo, la pérdida de la memoria cultural y la majestuosidad de la selva.",
        trailer: "https://youtu.be/31pfdpYLaCw?si=KJFQz7-oYMtF5NTm",
        year: "2015",
        director: "Ciro Guerra"
    },
    {
        id: 33,
        title: "Monos", 
        category: ["Drama", "Thriller", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.7, 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwoShyAdNooPdSLFnVZYa6HuNf3OQp6eaORQ&s", 
        description: "En la cima de una montaña remota y neblinosa de los Andes colombianos, un grupo de ocho adolescentes guerrilleros, apodados 'Los Monos', vigila a una prisionera estadounidense (la 'Doctora') y a una vaca lechera llamada Shakira. Lo que comienza como un entrenamiento riguroso en un entorno idílico pero salvaje, se convierte en un caos absoluto cuando la vaca muere accidentalmente y el grupo es forzado a desplazarse hacia la selva profunda. Allí, la estructura jerárquica se desmorona y los instintos más primitivos de los jóvenes salen a flote, transformando su supervivencia en una pesadilla de violencia y descontrol.",
        trailer: "https://youtu.be/EUrKRtE_Cxk?si=ZkqzihSqTLMH0x-j",
        year: "2019",
        director: "Alejandro Landes"
    },
    {
        id: 34,
        title: "La vendedora de rosas", 
        category: ["Drama", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.3, 
        img: "https://www.proimagenescolombia.com/photos/57150_993__imagen__.jpg", 
        description: "Inspirada en el cuento de Hans Christian Andersen, la película sigue a Mónica, una niña de 13 años que vive en las calles de Medellín durante la época de Navidad. Mónica sobrevive vendiendo rosas en las zonas de fiesta y discotecas, mientras se enfrenta a un entorno de violencia, drogas y abandono. La historia muestra de forma cruda y sin filtros la vida de un grupo de jóvenes olvidados por la sociedad, quienes, a pesar de la tragedia que los rodea, intentan encontrar momentos de alegría y dignidad en medio del caos.",
        trailer: "https://youtu.be/OKXFWW01Bhs?si=nkym6Eh3QIPXk8bG",
        year: "1998",
        director: "Víctor Gaviria"
    },
    {
        id: 35,
        title: "Gente de Bien", 
        category: ["Drama", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.5, 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk4ktY_pmnFm2j_oDhdkeFvI75kVaZiabS-g&s" , 
        description: "Eric es un niño de diez años que, tras ser abandonado por su madre, es enviado a vivir con su padre, Gabriel, un humilde carpintero que apenas logra sobrevivir económicamente. Gabriel trabaja para María Isabel, una mujer de clase alta que, movida por una mezcla de generosidad y lástima, decide llevarse al niño y a su padre a su casa de vacaciones durante el verano. Sin embargo, lo que parece ser un acto de caridad termina evidenciando las insalvables brechas sociales y la incomodidad de un niño que no siente pertenecer a ninguno de los dos mundos.",
        trailer: "https://youtu.be/5XD4waS2-bs?si=agHfa2_vLWpvt1qm",
        year: "2014",
        director: "Franco Lolli"
    },
    {
        id: 36,
        title: "Crash Landing on You", 
        category: ["Romance", "Drama", "Serie"], 
        type: "Serie", 
        rating: 4.9, 
        img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiHg66eVMtcmZXYUo7EUukmMXO25rfi1a9_4AR08iYjLfeTjQ5qQOgsZwxXr1UOyk-y4lX3gyARHAHCbUqDvYa9aoD7PoB_ZhjrSwez1nPOtMyR00Dz7bnMKdq_4rf-2dG98eqZQU59jUt3/s1600/crash-landing-on-you0.png" , 
        description: "Yoon Se-ri es una exitosa empresaria y heredera surcoreana que, mientras vuela en parapente, se ve atrapada en un tornado que la desvía de su curso. Termina aterrizando de emergencia en la Zona Desmilitarizada de Corea del Norte. Allí es encontrada por Ri Jeong-hyeok, un capitán del ejército norcoreano, quien decide no entregarla y, en cambio, esconderla en su casa mientras busca la forma de regresarla a su país. En el proceso, ambos deben navegar las peligrosas diferencias políticas entre sus naciones mientras surge un romance que parece imposible.",
        trailer: "https://youtu.be/eXMjTXL2Vks?si=PNJBi0e080mbr-vp",
        year: "2019–2020",
        director: "Lee Jeong-hyo"
    },
    {
        id: 37,
        title: "Kingdom", 
        category: ["Acción", "Terror", "Serie"], 
        type: "Serie", 
        rating: 4.4, 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVnN2Ly6P-0ebHdJti4ZALKDfCVZc2_to3DQ&s",
        description: "Ambientada en la época de la dinastía Joseon (siglo XV-XVI), la historia comienza con extraños rumores sobre la enfermedad del Rey. El Príncipe Heredero, Lee Chang, intenta visitar a su padre pero se le prohíbe el paso, lo que lo lleva a investigar por su cuenta. En su viaje hacia las provincias, descubre que una misteriosa plaga está resucitando a los muertos, convirtiéndolos en monstruos hambrientos de carne humana que solo atacan de noche. Mientras lucha por salvar al reino de la epidemia, el Príncipe también debe enfrentar una conspiración política de la poderosa familia Haewon Cho, que busca usurpar el trono.",
        trailer: "https://youtu.be/gmpqeBunw7Q?si=xFmZMsCc3KOGHaQ0",
        year: "2019",
        director: "Kim Seong-hun"
    },
    {
        id: 38,
        title: "Descendants of the Sun", 
        category: ["Romance", "Acción", "Serie"], 
        type: "Serie", 
        rating: 4.3, 
        img: "https://upload.wikimedia.org/wikipedia/en/6/6e/DescendantsoftheSun.jpg",
        description: "Yoo Si-jin es el carismático capitán de una unidad de fuerzas especiales surcoreana, y Kang Mo-yeon es una talentosa y decidida cirujana cardiovascular. Tras un breve e intenso romance interrumpido por sus opuestas visiones del mundo —él mata para proteger vidas, ella salva vidas cueste lo que cueste—, se separan. Sin embargo, el destino los reúne meses después en Uruk, un país ficticio devastado por la guerra y los desastres naturales. En este entorno extremo, ambos deben trabajar juntos para enfrentar epidemias, terremotos y conflictos armados, mientras redescubren su amor y aprenden a respetar el sacrificio que cada uno hace por su deber.",
        trailer: "https://youtu.be/wTGwjDqtfzQ?si=on17-BYTkIAYn62O",
        year: "2016",
        director: "Lee Eung-bok y Baek Sang-hoon"
    },
    {
        id: 39,
        title: "Vincenzo", 
        category: ["Acción", "Comedia", "Serie"], 
        type: "Serie", 
        rating: 3.3, 
        img: "https://m.media-amazon.com/images/M/MV5BNjA1YmJiNTMtMDc4OC00ZjlkLTgyMjctYzRmMWJhMmZhMjkyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        description: "A la edad de ocho años, Park Joo-hyung es adoptado por una familia italiana y crece bajo el nombre de Vincenzo Cassano. Años después, convertido en un frío abogado y 'consigliere' de la mafia italiana, regresa a Corea del Sur tras una guerra entre facciones para recuperar un cargamento de oro escondido bajo un viejo edificio, el Geumga Plaza. Sin embargo, se ve envuelto en una lucha contra el poderoso y corrupto Grupo Babel. Vincenzo decide aplicar la justicia a su manera: con la filosofía de que 'solo el mal puede castigar al mal', uniendo fuerzas con la audaz abogada Hong Cha-young.",
        trailer: "https://youtu.be/WO0xoDyGrdc?si=j9LgVpooc50HwrUN",
        year: "2021",
        director: "Kim Hee-won"
    },
    {
        id: 40,
        title: "It's Okay to Not Be Okay", 
        category: ["Romance", "Drama", "Serie"], 
        type: "Serie", 
        rating: 3.7, 
        img: "https://m.media-amazon.com/images/M/MV5BNWJhMDNjMWUtMWM5NS00MGZlLWI2MWQtODMxYjZiYmFlZjgzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        description: "La historia sigue a Moon Gang-tae, un empático enfermero de una unidad psiquiátrica que dedica su vida a cuidar de su hermano mayor, Sang-tae, quien tiene autismo. Debido a un trauma infantil, Gang-tae huye de los lazos emocionales y cambia de ciudad constantemente. Su vida da un giro cuando conoce a Ko Moon-young, una famosa escritora de libros infantiles con un trastorno de personalidad antisocial, que es egoísta, arrogante y obsesiva. A medida que sus vidas se entrelazan, los tres comienzan un proceso de sanación profunda, enfrentando sus traumas del pasado y descubriendo que la verdadera cura reside en la aceptación y el amor.",
        trailer: "https://youtu.be/50ek4HQo0Bc?si=zy-eBiSBNtqXrq81",
        year: "2020",
        director: "Park Shin-woo"
    },
    {
        id: 41,
        title: "Invincible", 
        category: ["Acción", "Animación", "Serie"], 
        type: "Serie", 
        rating: 4.7, 
        img: "https://m.media-amazon.com/images/M/MV5BZjE4ZDU4ZjMtZjliYS00M2ZmLThkNTItN2U3MmJjOGU0NmIxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg" ,
        description: "Mark Grayson parece un adolescente común, excepto por un detalle: su padre es Omni-Man, el superhéroe más poderoso del planeta. Poco después de cumplir 17 años, Mark finalmente desarrolla sus propios poderes y comienza a entrenar con su padre para convertirse en el héroe conocido como 'Invincible'. Sin embargo, mientras intenta equilibrar su vida escolar con sus nuevas responsabilidades, descubre que el legado de su padre no es tan heroico como el mundo cree y que la verdadera naturaleza de su origen esconde un secreto oscuro que pone en peligro a toda la humanidad.",
        trailer: "https://youtu.be/ROCIksHW2oc?si=2h_Aa8iodpoir30c",
        year: "2021",
        director: "Robert Kirkman"
    },
    {
        id: 42,
        title: "Daredevil", 
        category: ["Acción", "Crimen", "Serie"], 
        type: "Serie", 
        rating: 4.5, 
        img: "https://lumiere-a.akamaihd.net/v1/images/image003_86eb2e3f.jpeg?region=0,0,607,867",
        description: "Matt Murdock quedó ciego tras un accidente con desechos químicos cuando era niño, pero a cambio sus otros cuatro sentidos se agudizaron a niveles sobrehumanos. De día, es un abogado idealista que lucha por la justicia en el barrio neoyorquino de Hell's Kitchen; de noche, utiliza sus habilidades para combatir el crimen como el vigilante 'Daredevil'. Su principal enemigo es Wilson Fisk (Kingpin), un poderoso señor del crimen que intenta controlar la ciudad bajo una fachada de filantropía. La serie explora el conflicto moral de Matt entre su fe católica y la violencia que ejerce para salvar su hogar.",
        trailer: "https://youtu.be/7xALolZzhSM?si=N7OheIHnW_VenS5O",
        year: "2015–2018",
        director: "Drew Goddard / Steven S. DeKnight"
    },
    {
        id: 43,
        title: "Doom Patrol", 
        category: ["Comedia", "Sci-Fi", "Serie"], 
        type: "Serie", 
        rating: 4.6, 
        img: "https://es.web.img3.acsta.net/pictures/19/02/12/11/56/4356169.jpg" ,
        description: "La serie sigue a un grupo de personas que obtuvieron sus habilidades a través de circunstancias trágicas y horribles accidentes que los dejaron desfigurados y traumatizados. No son héroes, son parias que viven escondidos en una mansión bajo el cuidado de 'The Chief', un científico misterioso.",
        trailer: "https://youtu.be/tC334uVMys0?si=KXi45-425y7frPTG",
        year: "2019–2023",
        director: "Jeremy Carver"
    },
    {
        id: 44,
        title: "Loki", 
        category: ["Comedia", "Sci-Fi", "Serie"], 
        type: "Serie", 
        rating: 4.5, 
        img: "https://es.web.img2.acsta.net/pictures/21/05/12/16/27/2587198.jpg" ,
        description: "La historia comienza justo después de los eventos de Avengers: Endgame, cuando el Loki de 2012 escapa con el Teseracto. Sin embargo, su huida es interrumpida por la TVA (Autoridad de Variación Temporal), una organización burocrática que existe fuera del tiempo y el espacio y cuya función es podar las 'líneas temporales alternativas' para mantener la Sagrada Línea Temporal. Loki es arrestado como una 'variante' y se ve obligado a elegir: ser borrado de la existencia o ayudar al agente Mobius a detener una amenaza aún mayor: otra variante de sí mismo que está sembrando el caos a través de la historia.",
        trailer: "https://youtu.be/mjZmySwHKO0?si=ZEHTAirttmqNap8D",
        year: "2021–2023",
        director: "Kate Herron"
    },
    {
        id: 45,
        title: "The Umbrella Academy", 
        category: ["Sci-Fi", "Acción", "Serie"], 
        type: "Serie", 
        rating: 4.5, 
        img: "https://m.media-amazon.com/images/M/MV5BMzlmMmIxODItYzBjNC00YjMwLWIwOTAtNzVlMTBlNTNkMjZjXkEyXkFqcGc@._V1_.jpg" ,
        description: "En 1989, 43 mujeres que no estaban embarazadas dan a luz simultáneamente. Siete de esos niños son adoptados por el excéntrico multimillonario Sir Reginald Hargreeves, quien fundó la Umbrella Academy para entrenarlos y salvar el mundo. Años después, tras distanciarse por traumas familiares, los hermanos se reúnen tras la muerte de su padre. Sin embargo, el regreso de'Numero Cinco' del futuro trae una noticia aterradora: el apocalipsis ocurrirá en pocos días. Los hermanos deberán superar sus disfuncionales personalidades y sus oscuros pasados para detener el fin del mundo, mientras descubren secretos familiares que cambian todo lo que creían saber.",
        trailer: "https://youtu.be/KHucKOK-Vik?si=vKf2rYLXw-Pnuw_R",
        year: "2019–2024",
        director: "Steve Blackman"
    },
    {
        id: 46,
        title: "El exorcista", 
        category: ["Terror", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.5, 
        img: "https://m.media-amazon.com/images/M/MV5BZjg3YjE4ZjAtYTdmYS00ZTBkLWE1ZjgtNzAzODUwNzRiYjlmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg" ,
        description: "Regan es una niña de doce años que comienza a experimentar cambios drásticos en su comportamiento y físico: sufre convulsiones, levita y profiere insultos con una voz diabólica. Tras someterla a múltiples exámenes médicos que no arrojan resultados, su madre, desesperada, acude a la Iglesia. El Padre Karras, un sacerdote que atraviesa una crisis de fe, y el Padre Merrin, un arqueólogo y exorcista experimentado, se enfrentan en un duelo espiritual contra una entidad demoníaca antigua (Pazuzu) para intentar salvar el alma y la vida de la niña.",
        trailer: "https://youtu.be/LlTl5PoS1cE?si=m9376U6YBcwW62Am",
        year: "1973",
        director: "William Friedkin"
    },
    {
        id: 47,
        title: "The babadook", 
        category: ["Terror", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.3, 
        img: "https://m.media-amazon.com/images/M/MV5BMTk0NzMzODc2NF5BMl5BanBnXkFtZTgwOTYzNTM1MzE@._V1_FMjpg_UX1000_.jpg" ,
        description: "Amelia es una madre soltera que lucha por criar a su hijo de seis años, Samuel, tras la trágica muerte de su esposo el día que el niño nació. Samuel sufre de terrores nocturnos y está obsesionado con un monstruo que cree que viene a matarlos. Un día, aparece en su casa un extraño libro de cuentos titulado 'Mister Babadook'. A medida que Amelia lee el libro, una presencia siniestra comienza a manifestarse en la casa, alimentándose del agotamiento, el duelo reprimido y el resentimiento de la madre, llevando a ambos al borde de la locura.",
        trailer: "https://youtu.be/29qrvJMui0c?si=CAbdBC0TRJSnh_WU",
        year: "2014",
        director: "Jennifer Kent"
    },
    {
        id: 48,
        title: "Scream 2", 
        category: ["Terror", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.1, 
        img: "https://m.media-amazon.com/images/M/MV5BODE5YWJkMDMtN2ZiNC00MjI5LTkxYTgtOTkyZjUwMjU0YThiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"  ,
        description: "Dos años después de los terribles asesinatos en Woodsboro, Sidney Prescott intenta rehacer su vida en la Universidad de Windsor. Sin embargo, el estreno de la película Stab (basada en los crímenes del primer film) desencadena una nueva ola de asesinatos. Un nuevo imitador de Ghostface comienza a matar estudiantes siguiendo un patrón que parece imitar las muertes originales. Sidney, junto a los sobrevivientes Dewey y Gale Weathers, debe descubrir quién está detrás de la máscara antes de convertirse en la víctima final de una secuela que, según las reglas del cine, promete ser más sangrienta y elaborada.",
        trailer: "https://youtu.be/ZJcdPQEdSPc?si=HSTgcA7zM2mgIGey",
        year: "1997",
        director: "Wes Craven"
    },
    {
        id: 49,
        title: "Outlander", 
        category: ["Romance", "Fantasia", "Serie"], 
        type: "Serie", 
        rating: 4.8, 
        img: "https://images.justwatch.com/poster/34058043/s718/outlander.jpg"  ,
        description: "La historia comienza en 1945, justo después de la Segunda Guerra Mundial. Claire Randall, una enfermera de combate casada, disfruta de una segunda luna de miel en Escocia con su esposo Frank. Tras tocar unas piedras antiguas en el círculo de Craigh na Dun, Claire es transportada misteriosamente al año 1743. En este mundo desconocido y peligroso, se ve obligada a casarse con Jamie Fraser, un joven guerrero escocés caballeroso y romántico. Claire se encuentra dividida entre dos hombres, dos épocas y dos vidas completamente diferentes, mientras se ve envuelta en los levantamientos jacobitas que marcaron la historia de Escocia.",
        trailer: "https://youtu.be/PFFKjptRr7Y?si=UeDQGM9tGBM_Y_dE",
        year: "2014",
        director: "Metin Hüseyin, Anna Foerster, Jamie Payne"
    },
    {
        id: 50,
        title: "Normal People", 
        category: ["Romance", "Drama"], 
        type: "Serie", 
        rating: 4.6, 
        img: "https://images.justwatch.com/poster/176978990/s718/normal-people.jpg" ,
        description: "La serie sigue la compleja relación entre Marianne Sheridan y Connell Waldron a lo largo de varios años, desde sus últimos días en el instituto en un pequeño pueblo de Irlanda hasta sus años universitarios en el Trinity College de Dublín. En el instituto, Connell es un atleta popular y Marianne una solitaria orgullosa e intimidante; sin embargo, entre ellos surge una conexión eléctrica que deciden mantener en secreto. A medida que crecen, sus roles sociales se invierten y sus vidas se entrelazan y separan constantemente, explorando cómo las inseguridades, la falta de comunicación y sus diferentes contextos familiares moldean su identidad y su amor.",
        trailer: "https://youtu.be/x1JQuWxt3cE?si=wykJ22_4JJn9e4N-",
        year: "2020",
        director: "Lenny Abrahamson / Hettie Macdonald"
    },
    {
        id: 51,
        title: "You Are the Worst", 
        category: ["Romance", "Comedia", "Serie"], 
        type: "Serie", 
        rating: 4.6, 
        img: "https://m.media-amazon.com/images/M/MV5BMTU4OTM5OTM2NV5BMl5BanBnXkFtZTgwNDc3MDg0MzI@._V1_.jpg" ,
        description: "La serie comienza cuando Jimmy, un escritor británico narcisista y egoísta, conoce a Gretchen, una publicista de música autodestructiva y cínica, en la boda de la exnovia de Jimmy (a la que él asistió solo para burlarse). Tras una aventura de una noche, ambos que se consideran 'incapaces de amar' y detestan las convenciones sociales terminan intentando entablar una relación. La historia sigue su romance poco convencional mientras intentan navegar la vida adulta junto a sus amigos: Edgar, un veterano de guerra con estrés postraumático, y Lindsay, la mejor amiga de Gretchen que está atrapada en un matrimonio aburrido.",
        trailer: "https://youtu.be/4ao_jIEqRgg?si=xYo5kywSUkeJ_Ux_",
        year: "2014 – 2019",
        director: "Alex Hardcastle, Wendey Stanzler, Matt Shakman"
    },
    {
        id: 52,
        title: "Pachinko", 
        category: ["Romance", "Drama", "Serie"], 
        type: "Serie", 
        rating: 4.3, 
        img: "https://m.media-amazon.com/images/M/MV5BN2QwMTgyZTAtOTM4MS00OGRhLWIzNjQtZmQ3Yzc5NmNiYzhlXkEyXkFqcGc@._V1_.jpg" ,
        description: "La historia comienza en la Corea de principios de 1900, bajo la ocupación japonesa. Sunja, una joven humilde y valiente, se ve envuelta en un romance que la obliga a abandonar su hogar y emigrar a Japón para salvar su honor. La narrativa salta constantemente en el tiempo, conectando la vida de Sunja con la de su nieto, Solomon, en la década de 1980. Solomon es un ejecutivo educado en EE. UU. que intenta cerrar un trato inmobiliario en Tokio, lo que lo obliga a confrontar el racismo sistemático que su familia ha sufrido como inmigrantes coreanos en Japón (Zainichi) y el peso del sacrificio de su abuela.",
        trailer: "https://youtu.be/UjzvmvnTmCA?si=iufgJKEGFsfc7r7d",
        year: "2022",
        director: "Kogonada"
    },
    {
        id: 53,
        title: "One Day (Siempre el mismo día)", 
        category: ["Romance", "Drama", "Serie"], 
        type: "Serie", 
        rating: 4.4, 
        img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRrazBQBAWZpOgkjddl_TBV7z_UUQWGcRmAhV7gGMHebAcnPFDe" ,
        description: "La historia sigue a Emma Morley y Dexter Mayhew, quienes hablan por primera vez el 15 de julio de 1988, la noche de su graduación universitaria. A la mañana siguiente, cada uno sigue su camino, pero la narrativa nos muestra sus vidas siempre el mismo día (el 15 de julio) a lo largo de veinte años. Vemos cómo crecen, se alejan, se pelean, triunfan, fracasan y, sobre todo, cómo evoluciona ese vínculo inquebrantable que tienen, mientras el espectador se pregunta si finalmente el destino los unirá de forma permanente.",
        trailer: "https://youtu.be/h6y_0WsHW8U?si=EShIklFCh8_abY7G",
        year: "2024",
        director: "Molly Manners, Luke Snellin, John Hardwick y Kate Hewitt."
    },
    {
        id: 54,
        title: "Friends", 
        category: ["Comedia", "Serie"], 
        type: "Serie", 
        rating: 4.9, 
        img: "https://m.media-amazon.com/images/M/MV5BOTU2YmM5ZjctOGVlMC00YTczLTljM2MtYjhlNGI5YWMyZjFkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        description: "La serie sigue las vidas, amores y carreras de seis amigos en sus veintes y treintas que viven en el barrio de Greenwich Village, en Manhattan, Nueva York. El grupo está compuesto por la consentida Rachel, la obsesiva chef Monica, el sarcástico Chandler, el ingenuo actor Joey, la excéntrica Phoebe y el tierno paleontólogo Ross. Entre tazas de café en el Central Perk y las paredes del apartamento de Monica, el grupo navega por los altibajos de la vida adulta, demostrando que, cuando la familia no está cerca, los amigos son los que siempre están ahí para ti.",
        trailer: "https://youtu.be/ki6Mbtnl_9I?si=durTmrbAXF7iWbLm",
        year: "1994 – 2004",
        director: "Gary Halvorson, Kevin S. Bright, Michael Lembeck."
    },
    {
        id: 55,
        title: "Brooklyn Nine-Nine", 
        category: ["Comedia", "Crimen", "Serie"], 
        type: "Serie", 
        rating: 4.6, 
        img: "https://m.media-amazon.com/images/M/MV5BNzBiODQxZTUtNjc0MC00Yzc1LThmYTMtN2YwYTU3NjgxMmI4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg" ,
        description: "La serie se desarrolla en la comisaría 99 del NYPD en Brooklyn. La trama sigue a Jake Peralta, un detective extremadamente talentoso pero inmaduro que disfruta haciendo bromas y viviendo como si estuviera en una película de acción. Su vida cambia con la llegada del nuevo capitán, Raymond Holt, un hombre robóticamente serio, estricto y el primer capitán negro abiertamente gay del departamento. La dinámica entre el caos de Peralta y la disciplina de Holt, junto a un elenco de detectives excéntricos, crea un ambiente de oficina donde los casos criminales a menudo pasan a segundo plano frente a las locas apuestas y la profunda amistad del equipo.",
        trailer: "https://youtu.be/sEOuJ4z5aTc?si=xAP8bPItP3r6iscT",
        year: "2013 – 2021",
        director: "Michael McDonald, Linda Mendoza, Beth McCarthy-Miller y Claire Scanlon."
    },
    {
        id: 56,
        title: "Seinfeld", 
        category: ["Comedia", "Serie"], 
        type: "Serie", 
        rating: 4.5, 
        img: "https://m.media-amazon.com/images/M/MV5BMmRjNjZjN2ItN2FkYi00ZDg0LWExN2EtMTU2ODUwNWU1M2NhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        description: "La serie sigue la vida cotidiana de una versión ficticia de Jerry Seinfeld, un comediante de stand-up en Nueva York, y su grupo de amigos: su neurótico y fracasado mejor amigo George Costanza, su inteligente y asertiva exnovia Elaine Benes, y su excéntrico y entrometido vecino Cosmo Kramer. A diferencia de otras comedias de la época, no hay lecciones de vida ni momentos sentimentales; la trama se centra en las minucias de la vida moderna, las reglas sociales absurdas y los problemas triviales que terminan escalando hasta situaciones catastróficas.",
        trailer: "https://youtu.be/N42iSWZjKxA?si=JColCpeTffPaIva7",
        year: "1989 – 1998",
        director: "Tom Cherones, Andy Ackerman"
    },
    {
        id: 57,
        title: "Parks and Recreation", 
        category: ["Comedia", "Serie"], 
        type: "Serie", 
        rating: 4.5, 
        img: "https://m.media-amazon.com/images/M/MV5BNDlhMzAwNTAtNTk2NS00MTdkLWE3ZWYtMDU0MTFiYmU2ZTc0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg" ,
        description: "La serie adopta el formato de falso documental (mockumentary) para seguir a Leslie Knope, una funcionaria de nivel medio en el Departamento de Parques y Recreación de Pawnee, Indiana. Leslie es una mujer extremadamente entusiasta, trabajadora y amante de la burocracia que sueña con convertirse en la primera mujer presidenta de EE. UU. Su misión principal comienza con algo simple: convertir un pozo de construcción abandonado en un parque. Para lograrlo, debe lidiar con ciudadanos excéntricos, políticos corruptos y sus propios compañeros de oficina, liderados por un jefe que odia al gobierno tanto como ama la carne roja.",
        trailer: "https://youtu.be/5IZWeAwdJ-s?si=EhGAe2088kf3t0Xg",
        year: "2009 – 2015",
        director: "TDean Holland, Ken Kwapis, Michael Schur y Nicole Holofcener."
    },
    {
        id: 58,
        title: "Ted Lasso", 
        category: ["Comedia", "Drama", "Serie"], 
        type: "Serie", 
        rating: 4.6, 
        img: "https://m.media-amazon.com/images/M/MV5BZmI3YWVhM2UtNDZjMC00YTIzLWI2NGUtZWIxODZkZjVmYTg1XkEyXkFqcGc@._V1_.jpg" ,
        description: "Ted Lasso, un optimista entrenador de fútbol americano universitario con nula experiencia en el fútbol europeo, es contratado para dirigir al AFC Richmond, un equipo de la Premier League inglesa. Lo que Ted no sabe es que la dueña del club, Rebecca Welton, lo ha contratado solo para que el equipo fracase y así vengarse de su exmarido. Sin embargo, el arma secreta de Ted no es su táctica deportiva, sino su empatía inagotable y su capacidad para transformar a las personas, ganándose poco a poco el respeto de los jugadores, la prensa y la propia Rebecca.",
        trailer: "https://youtu.be/TMPUlfH-stE?si=DOY9Kq9f5Zu5IgvL",
        year: "2020 – 2023",
        director: "MJ Delaney, Declan Lowney, Destin Daniel Cretton, Zach Braff."
    },
    {
        id: 59,
        title: "paddington", 
        category: ["Comedia", "Familia", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.8, 
        img: "https://m.media-amazon.com/images/I/81ajUVs6ddL.jpg" ,
        description: "Un joven oso peruano con una pasión por todo lo británico viaja a Londres en busca de un hogar tras un devastador terremoto en su selva. Al llegar a la estación de Paddington, se encuentra perdido y solo, dándose cuenta de que la vida en la ciudad no es como se la imaginaba... hasta que conoce a la familia Brown. Ellos lo acogen temporalmente y lo llaman como la estación donde lo encontraron. Sin embargo, su presencia en Londres llama la atención de una malvada taxidermista de un museo, Millicent Clyde, quien está decidida a capturarlo para su colección.",
        trailer: "https://youtu.be/Bt4J4MVuHXE?si=DMnA7y1vpt3WWgIl",
        year: "2014",
        director: "Paul King"
    },
    {
        id: 60,
        title: "Spider-Man: Un Nuevo Universo (Spider-Verse)", 
        category: ["Comedia", "Acción", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.9, 
        img: "https://m.media-amazon.com/images/M/MV5BOTNlZDY2NzktNDQwMS00ZWE4LWE3MmMtNGUzZTJhMmQ0NGI1XkEyXkFqcGc@._V1_.jpg",
        description: "La historia presenta a Miles Morales, un adolescente de Brooklyn que lucha por adaptarse a su nueva escuela y cumplir las expectativas de su padre. Tras ser mordido por una araña radioactiva, Miles desarrolla poderes similares a los de Spider-Man, pero pronto presencia la muerte del Peter Parker de su universo. Sin embargo, un experimento fallido del Kingpin abre portales a otras dimensiones, trayendo a diferentes versiones de Spider-Man (incluyendo a un Peter Parker más viejo y cansado, a Spider-Gwen, Spider-Man Noir y hasta a Spider-Ham). Miles deberá aprender a ser un héroe para ayudar a los demás 'Spider-People' a regresar a sus mundos y salvar el multiverso.",
        trailer: "https://youtu.be/k-8ZFn1Askc",
        year: "2018",
        director: "Bob Persichetti, Peter Ramsey, Rodney Rothman."
    },
    {
        id: 61,
        title: "El Rey León (The Lion King)", 
        category: ["Comedia", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.9, 
        img: "https://m.media-amazon.com/images/M/MV5BNjExYTQwY2EtMDRkYi00ZWIzLTkwZDUtYjVmODYxMDUwNDI5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg" ,
        description: "En las Tierras del Reino, nace el príncipe león Simba, heredero al trono de su padre, el sabio rey Mufasa. Sin embargo, el malvado tío de Simba, Scar, conspira para usurpar el trono provocando una tragedia que obliga a Simba a exiliarse. En su huida, conoce a la divertida pareja formada por el suricato Timón y el facóquero Pumba, quienes le enseñan su filosofía de vida 'Hakuna Matata'. Años más tarde, tras un encuentro inesperado con su pasado, Simba deberá decidir si regresa para enfrentar su destino y reclamar su lugar en el 'Ciclo de la Vida'",
        trailer: "https://youtu.be/bjJvvrKl83M",
        year: "1994",
        director: "Roger Allers y Rob Minkoff"
    },
    {
        id: 62,
        title: "Harry Potter 1", 
        category: ["Comedia", "Fantasia", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.8, 
        img: "https://play-lh.googleusercontent.com/8iZjDOMW5B4Xuk1Qv8VtrAy-TYGRX9_YOcvoPeSLbO1Vs78SQN71aTpFH2jnFO8RQnU",
        description: "Harry Potter es un niño huérfano que vive una vida miserable con sus tíos, los Dursley, quienes lo mantienen en la oscuridad sobre su verdadera identidad. Todo cambia en su undécimo cumpleaños, cuando recibe la visita de Hagrid, un gigante bondadoso que le revela que es un mago. Harry es invitado a estudiar en el Colegio Hogwarts de Magia y Hechicería. Allí descubrirá que es famoso por haber sobrevivido a un ataque del mago oscuro más temido, Voldemort, y junto a sus nuevos amigos Ron y Hermione, deberá proteger un objeto legendario: la Piedra Filosofal.",
        trailer: "https://youtu.be/ZgrCZVjPg9g?si=GngZHD2Q0BQ4RVUK",
        year: "2001",
        director: "Chris Columbus"
    },
    {
        id: 63,
        title: "Supermascotas", 
        category: ["Comedia", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.4, 
        img: "https://es.web.img3.acsta.net/pictures/22/06/08/14/52/2247090.jpg" ,
        description: "Krypto el Superperro y Superman son mejores amigos inseparables, comparten los mismos superpoderes y luchan contra el crimen en Metrópolis codo con codo. Sin embargo, cuando Superman y el resto de la Liga de la Justicia son secuestrados por la malvada conejilla de indias Lulu (que tiene poderes telequinéticos), Krypto pierde sus habilidades por culpa de la kryptonita. Para rescatarlos, deberá entrenar a un grupo de animales de un refugio que acaban de adquirir poderes accidentalmente: Ace (fuerza e invulnerabilidad), PB (puede cambiar de tamaño), Merton (supervelocidad) y Chip (poderes eléctricos).",
        trailer: "https://youtu.be/SKN1yVbdJ1g?si=F8kiITJOqBzk5E8y",
        year: "2022",
        director: "Jared Stern y Sam Levine."
    },
    {
        id: 64,
        title: "Sonic 3: la película", 
        category: ["Comedia", "Acción", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.8, 
        img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSu8nsDSE6dU7T3vTQShr0OgDHiCZSetzqGfkwV46_RphV-NogS" ,
        description: "Tras los eventos de la segunda película, el Equipo Sonic (Sonic, Tails y Knuckles) disfruta de su vida en la Tierra, pero una nueva amenaza surge desde las sombras: Shadow el Erizo. Creado hace 50 años en un experimento secreto del gobierno llamado 'Proyecto Shadow', este nuevo erizo tiene poderes que superan a los de Sonic en todos los sentidos y busca venganza por una tragedia de su pasado. La situación es tan crítica que Sonic y sus amigos se ven obligados a formar una alianza improbable con su mayor enemigo, el Dr. Robotnik, para intentar detener a Shadow antes de que destruya el planeta.",
        trailer: "https://youtu.be/ySkQCd7UOhk?si=DY14sErKUIPMWjrA",
        year: "2024",
        director: "Jeff Fowler"
    },
    {
        id: 65,
        title: "Stranger Things", 
        category: ["Sci-Fi", "Terror", "Serie"], 
        type: "Serie", 
        rating: 4.6, 
        img: "https://pics.filmaffinity.com/stranger_things-875025085-large.jpg" ,
        description: "La historia comienza en 1983 en el pequeño y ficticio pueblo de Hawkins, Indiana. La desaparición misteriosa de un niño llamado Will Byers desata una serie de eventos sobrenaturales. Mientras sus amigos (Mike, Dustin y Lucas) lo buscan, se encuentran con una niña con poderes telequinéticos llamada Once (Eleven). Pronto descubren que el gobierno está realizando experimentos secretos que han abierto un portal a una dimensión alternativa y aterradora llamada el Mundo del Revés (Upside Down), liberando criaturas que amenazan con destruir su realidad.",
        trailer: "https://youtu.be/Wre1F5YyIlA?si=W-I13lfqtPtV8PMs",
        year: "2016",
        director: "The Duffer Brothers"
    },
    {
        id: 66,
        title: "El Demoledor", 
        category: ["Sci-Fi", "Acción", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.6, 
        img: "https://m.media-amazon.com/images/M/MV5BNWY3ZThmN2QtMzVkNS00MjczLTllNDQtOGEwN2M0ZTFkMWMzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg" ,
        description: "En 1996, el sargento de policía John Spartan (Sylvester Stallone) logra capturar al psicópata Simon Phoenix (Wesley Snipes), pero ambos son condenados a la 'Crioprisión' tras ser acusados de causar la muerte de civiles durante el rescate. En el año 2032, la ciudad de San Ángeles (una fusión de Los Ángeles y San Diego) es una utopía pacífica y ultracontrolada donde el crimen no existe. Cuando Phoenix escapa de su sueño criogénico, la policía del futuro no sabe cómo detener a alguien tan violento. La única solución es descongelar al 'Demoledor', el único hombre capaz de pelear sucio para atrapar a un monstruo.",
        trailer: "https://youtu.be/0B5v6QZ5R3g?si=yNzogCuQwRjjyZTU",
        year: "1993",
        director: "Marco Brambilla"
    },
    {
        id: 67,
        title: "Sonic: la película", 
        category: ["Comedia", "Acción", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.7, 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTiSbcfDZzTT0iEYYtQwedcnj-w1nd8BNsDQ&s",
        description: "Sonic, un erizo azul extraterrestre con la capacidad de correr a velocidades supersónicas, vive oculto en la Tierra, en el pequeño pueblo de Green Hills. Tras causar accidentalmente un apagón masivo, atrae la atención del gobierno de EE. UU., que envía al brillante pero desquiciado Dr. Robotnik para capturarlo. Sonic une fuerzas con el sheriff local, Tom Wachowski, en una aventura por carretera hacia San Francisco para recuperar sus anillos mágicos y escapar de las garras de Robotnik, quien planea usar la energía del erizo para dominar el mundo.",
        trailer: "https://youtu.be/MsaAnA2EZQg?si=Wz8P8RuLgki3IAcr",
        year: "2020",
        director: "Jeff Fowler"
    },
    {
        id: 68,
        title: "Superman (2025)", 
        category: ["Acción", "Sci-Fi", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.6, 
        img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS5kpHGfBNwXEl1mnr2LkSRjRIe1oqKe5VxbbVk42niymTQVzYR" ,
        description: "La historia se aleja de los orígenes tradicionales (no veremos de nuevo la muerte de Krypton ni a los Kent encontrando la nave). En su lugar, nos presenta a un Clark Kent más joven que ya trabaja en el Daily Planet en Metrópolis y ya opera como Superman. La trama se centra en el esfuerzo de Clark por reconciliar su herencia kryptoniana con su educación humana basada en la bondad y la verdad. En un mundo donde los superhéroes ya existen y a veces son cínicos o violentos, Superman debe demostrar que ser una 'buena persona' todavía es relevante.",
        trailer: "https://youtu.be/tnqje4O31mg?si=jNJ1ronhPbBS6nwA",
        year: "2025",
        director: "James Gunn"
    },
    {
        id: 69,
        title: "Mi Villano Favorito 4", 
        category: ["Comedia", "Animación", "Pelicula"], 
        type: "Pelicula", 
        rating: 3.1, 
        img: "https://dx35vtwkllhj9.cloudfront.net/universalstudios/despicable-me-4/images/regions/us/onesheet.jpg",
        description: "Gru, que ahora trabaja a tiempo completo para la Liga Antivillanos (LAV), se enfrenta a un desafío doble. Por un lado, debe lidiar con la llegada de su hijo biológico, Gru Jr., quien parece disfrutar atormentando a su padre. Por otro lado, un antiguo rival de la escuela de villanos, Maxime Le Mal, escapa de prisión junto a su novia Valentina jurando venganza contra Gru. Esto obliga a toda la familia a entrar en un programa de protección de testigos, mudándose a una ciudad pija bajo identidades falsas, mientras cinco Minions son elegidos para recibir superpoderes y convertirse en los Mega Minions.",
        trailer: "https://youtu.be/I0_qFoptZ4Y?si=_D1hRYhYnGtb6f6m",
        year: "2024",
        director: "Chris Renaud"
    },
    {
        id: 70,
        title: "Alien: Romulus", 
        category: ["Terror", "Sci-Fi", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.3, 
        img: "https://m.media-amazon.com/images/M/MV5BZmViMjcyYzMtMzdmYi00MjVmLWFhYjQtN2U1ZTU0YWIzNDhlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        description: "Un grupo de jóvenes colonos espaciales, que viven en condiciones miserables en una colonia minera sin sol, deciden asaltar una estación de investigación de la corporación Weyland-Yutani aparentemente abandonada, con la esperanza de encontrar cámaras de criogenia que les permitan escapar a un planeta mejor. Sin embargo, al llegar a la estación (dividida en los módulos Rómulo y Remo), descubren que no están solos: han entrado directamente en el nido de la forma de vida más aterradora y perfecta del universo.",
        trailer: "https://youtu.be/5nWH2Pd-x-c?si=K2ACpt9arnHWx4fw",
        year: "2024",
        director: "Fede Álvarez"
    },
    {
        id: 71,
        title: "Misión imposible: sentencia mortal Parte 2", 
        category: ["Acción", "Thriller", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.7, 
        img: "https://m.media-amazon.com/images/S/pv-target-images/f5af184404f22183d9511e2baff600f18d32277ed826ff23a815a9129d3c8f2b.jpg" ,
        description: "Tras los eventos de la primera parte, Ethan Hunt (Tom Cruise) y su equipo del FMI continúan la búsqueda desesperada del 'Entidad', una inteligencia artificial consciente y todopoderosa que puede manipular cualquier red digital del planeta. El objetivo final es encontrar el submarino hundido Sebastopol, que contiene el núcleo de la IA y la única forma de destruirla o controlarla. Ethan no solo debe enfrentarse a la tecnología, sino también a su pasado en la figura de Gabriel, mientras las potencias mundiales luchan por hacerse con el control de un arma que cambiaría el orden global para siempre.",
        trailer: "https://youtu.be/B8-eBVeEBFA?si=C_kzdlMpdgLZAvZk",
        year: "2025",
        director: "Christopher McQuarrie"
    },
    {
        id: 72,
        title: "Misión imposible: sentencia mortal Parte 1", 
        category: ["Acción", "Thriller", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.8, 
        img: "https://pics.filmaffinity.com/Misiaon_imposible_Sentencia_mortal_Parte_1-902615661-large.jpg" ,
        description: "Ethan Hunt y su equipo del FMI se embarcan en su misión más peligrosa hasta la fecha: localizar una nueva y aterradora arma, una Inteligencia Artificial conocida como 'La Entidad', que amenaza a toda la humanidad si cae en las manos equivocadas. Con el control del futuro y el destino del mundo en juego, y fuerzas oscuras del pasado de Ethan acechando, comienza una carrera mortal alrededor del globo. Enfrentado a un némesis misterioso y todopoderoso llamado Gabriel, Ethan se ve obligado a considerar que nada puede importar más que su misión, ni siquiera las vidas de aquellos que más le importan.",
        trailer: "https://youtu.be/HlF72YxIWWo?si=RuHOzLnPPKClXrC1",
        year: "2023",
        director: "Christopher McQuarrie"
    },
    {
        id: 73,
        title: "Mad Max: Furia en el Camino", 
        category: ["Acción", "Sci-Fi", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.9, 
        img: "https://m.media-amazon.com/images/M/MV5BODE2NWUwYmYtYmNmZi00OTVjLTgxMzEtZWYyMWVmODg5MmM2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg" ,
        description: "Max (ahora interpretado por Tom Hardy) se une a Imperator Furiosa (Charlize Theron) en una huida desesperada a través del desierto en un camión de guerra, escapando del tirano Immortan Joe, quien las persigue con todo su ejército.",
        trailer: "https://youtu.be/GvsFoGIuRX4?si=yue6kpeStvNP6OST",
        year: "2015",
        director: "George Miller"
    },
    {
        id: 74,
        title: "John Wick 1", 
        category: ["Acción", "Crimen", "Pelicula"], 
        type: "Pelicula", 
        rating: 5.0, 
        img: "https://es.web.img3.acsta.net/pictures/14/10/01/14/18/135831.jpg" ,
        description: "John Wick es un legendario asesino retirado que intenta llevar una vida tranquila tras la muerte de su esposa. Ella le deja un último regalo: un cachorro de beagle llamado Daisy, para que tenga algo a lo que aferrarse. Sin embargo, el hijo de un mafioso ruso, sin saber quién es John, irrumpe en su casa, le roba su Mustang del 69 y mata al cachorro. Este acto de violencia despierta al 'Baba Yaga' (el hombre del saco), quien desentierra sus armas del sótano para emprender una sangrienta venganza contra toda la organización criminal.",
        trailer: "https://youtu.be/r1u1zWsY4DU?si=-WgSjEdIKK1wyCun",
        year: "2014",
        director: "Chad Stahelski, David Leitch"
    },
    {
        id: 75,
        title: "Duro de Matar", 
        category: ["Acción", "Thriller", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.9, 
        img: "https://m.media-amazon.com/images/M/MV5BYzliYWVmYjEtYWYyMi00MDBlLTk5MjMtYTQ1OWQ2MzVmMzRiXkEyXkFqcGc@._V1_.jpg" ,
        description: "El policía de Nueva York John McClane viaja a Los Ángeles en vísperas de Navidad para intentar reconciliarse con su esposa, Holly, en la fiesta de su empresa en el moderno rascacielos Nakatomi Plaza. Sin embargo, la celebración es interrumpida por un grupo de terroristas altamente preparados, liderados por el sofisticado Hans Gruber, que toman el edificio y a todos los invitados como rehenes. McClane, descalzo y solo con su arma reglamentaria, logra ocultarse y comienza una guerra de guerrillas contra los terroristas para salvar a los rehenes y a su esposa.",
        trailer: "https://youtu.be/PVw40p8ZLkw?si=D3Y7NXk0sLY3Bk3j",
        year: "1994",
        director: "John McTiernan"
    },
    {
        id: 76,
        title: "Atómica (Atomic Blonde)", 
        category: ["Acción", "Thriller", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.1, 
        img: "https://es.web.img2.acsta.net/pictures/17/07/10/12/54/213732.jpg" ,
        description: "Ambientada en 1989, justo antes de la caída del Muro de Berlín, la trama sigue a Lorraine Broughton, una espía de élite del MI6 enviada a Alemania para recuperar una lista de agentes encubiertos que ha sido robada. En una ciudad llena de traiciones, agentes dobles y peligro constante, Lorraine debe unir fuerzas con el jefe de la estación local, David Percival (James McAvoy), para sobrevivir a una red de espionaje internacional que amenaza con destruir todo el sistema de inteligencia occidental.",
        trailer: "https://youtu.be/L1FLysSTV8Y?si=kokUbyAHBQ3DHZtd",
        year: "2017",
        director: "David Leitch"
    },
    {
        id: 77,
        title: "Memento", 
        category: ["Drama", "Thriller", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.4, 
        img: "https://m.media-amazon.com/images/M/MV5BMGQ3Y2Q4NjktN2E4Ny00Y2Q2LTliZDUtZTNiNjRhY2I0NGIyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        description: "Leonard Shelby (Guy Pearce) es un hombre que sufre de amnesia anterógrada, una condición que le impide crear nuevos recuerdos tras un trauma cerebral. Su último recuerdo nítido es el asesinato de su esposa, y su única motivación es encontrar al culpable para vengarse. Para lograrlo en un mundo que olvida cada 15 minutos, utiliza un sistema complejo de fotografías Polaroid, notas y tatuajes en su propio cuerpo que le indican en quién confiar y qué ha descubierto hasta el momento.",
        trailer: "https://youtu.be/mV9l1enMqvk?si=knVGCsK1jnzQ9f4V",
        year: "2000",
        director: "Christopher Nolan"
    },
    {
        id: 78,
        title: "La isla siniestra", 
        category: ["Drama", "Thriller", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.5, 
        img: "https://m.media-amazon.com/images/M/MV5BN2FjNWExYzEtY2YzOC00YjNlLTllMTQtNmIwM2Q1YzBhOWM1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg" ,
        description: "En 1954, los agentes federales Teddy Daniels (DiCaprio) y su nuevo compañero Chuck Aule (Mark Ruffalo) viajan a Ashecliffe, un hospital psiquiátrico para criminales peligrosos situado en una remota isla de Massachusetts. Su misión es investigar la desaparición de Rachel Solando, una paciente que parece haberse esfumado de una habitación cerrada bajo llave. A medida que un huracán azota la isla y los médicos (liderados por el enigmático Dr. Cawley) se muestran poco colaborativos, Teddy empieza a sospechar que en el hospital se realizan experimentos inhumanos... y que su propia llegada a la isla no fue una coincidencia.",
        trailer: "https://youtu.be/5iaYLCiq5RM?si=3kTKDblBFL9lBCas",
        year: "2010",
        director: "Martin Scorsese"
    },
    {
        id: 79,
        title: "Sospechosos Habituales (The Usual Suspects)", 
        category: ["Drama", "Crimen", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.7, 
        img: "https://pics.filmaffinity.com/the_usual_suspects-480334080-large.jpg" ,
        description: "Tras una explosión en un barco en el puerto de Los Ángeles que deja 27 muertos y solo dos supervivientes, el agente Kujan interroga a uno de ellos: 'Verbal' Kint (Kevin Spacey), un estafador con parálisis cerebral. Verbal explica que todo empezó seis semanas antes, cuando cinco criminales fueron detenidos para una rueda de reconocimiento por un robo de camiones. Juntos, deciden vengarse de la policía y terminan siendo chantajeados por el legendario y temido cerebro criminal Keyser Söze, un hombre al que nadie ha visto y que parece una figura mítica del mal.",
        trailer: "https://youtu.be/fVG7U5l9Pc0?si=LBLgVJbEW9dW_gS5",
        year: "1995",
        director: "Bryan Singer"
    },
    {
        id: 80,
        title: "Prisioneros (Prisoners)", 
        category: ["Drama", "Thriller", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.3, 
        img: "https://pics.filmaffinity.com/prisoners-721879978-large.jpg" ,
        description: "En un frío Día de Acción de Gracias, dos familias vecinas ven cómo sus pesadillas se hacen realidad cuando sus hijas pequeñas desaparecen sin dejar rastro mientras jugaban fuera. La policía detiene a un sospechoso, Alex Jones (Paul Dano), un joven con discapacidad intelectual que conducía una caravana cerca del lugar, pero el detective Loki (Jake Gyllenhaal) se ve obligado a liberarlo por falta de pruebas físicas. Desesperado y convencido de que Alex sabe dónde está su hija, Keller Dover (Hugh Jackman) decide tomar la justicia por su mano, secuestrando al joven y sometiéndolo a torturas brutales para hacerlo hablar, mientras Loki intenta resolver el rompecabezas de forma legal.",
        trailer: "https://youtu.be/AiN1ahjVb3Y?si=Gkmxl-_EVsVdRKWD",
        year: "2013",
        director: "Denis Villeneuve"
    },
    {
        id: 81,
        title: "Parásitos (Parasite)", 
        category: ["Drama", "Thriller", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.3, 
        img: "https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_.jpg",
        description: "La familia Kim vive en un semisótano estrecho, sobreviviendo con trabajos precarios y robando el Wi-Fi de los vecinos. Su suerte cambia cuando el hijo, Gi-woo, consigue un empleo como tutor de inglés para la hija de la adinerada familia Park. Mediante engaños y astucia, los cuatro miembros de la familia Kim logran infiltrarse en la mansión de los Park, ocupando puestos de servicio (chófer, ama de llaves, tutores). Sin embargo, cuando parece que su plan es perfecto, descubren un secreto oculto en el sótano de la casa que desata una espiral de violencia y caos impredecible.",
        trailer: "https://youtu.be/90dWVETAdtI?si=jQDnUZYKOQfeYMXC",
        year: "2019",
        director: "Bong Joon-ho"
    },
    {
        id: 82,
        title: "Mi pobre angelito", 
        category: ["Comedia", "Familia", "Pelicula"], 
        type: "Pelicula", 
        rating: 5.0, 
        img: "https://images.justwatch.com/poster/101468484/s718/home-alone.jpg",
        description: "Cuando la numerosa familia McCallister sale apresurada hacia el aeropuerto para pasar las vacaciones de Navidad en París, olvidan accidentalmente a uno de sus miembros: Kevin, un niño de ocho años que se queda solo en su enorme casa de Chicago. Aunque al principio Kevin disfruta de su libertad comiendo pizza y viendo películas prohibidas, pronto debe enfrentarse a dos ladrones de poca monta, Harry y Marv (los 'Bandidos Mojados'), que planean robar la mansión. Kevin decide proteger su hogar montando una serie de trampas ingeniosas y dolorosas para los invasores.",
        trailer: "https://youtu.be/jEDaVHmw7r4?si=z-nXftqDUxC5ta-A",
        year: "1990",
        director: "Chris Columbus"
    },
    {
        id: 83,
        title: "Seven (Se7en)", 
        category: ["Drama", "Crimen", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.6, 
        img: "https://m.media-amazon.com/images/M/MV5BY2IzNzMxZjctZjUxZi00YzAxLTk3ZjMtODFjODdhMDU5NDM1XkEyXkFqcGc@._V1_.jpg" ,
        description: "En una ciudad anónima, sombría y donde siempre llueve, el veterano detective William Somerset (Morgan Freeman), a solo una semana de jubilarse, debe trabajar con el impulsivo y joven detective David Mills (Brad Pitt). Ambos se enfrentan a una serie de asesinatos atroces cometidos por un psicópata que utiliza los siete pecados capitales (Gula, Codicia, Pereza, Lujuria, Soberbia, Envidia e Ira) como su modus operandi para castigar a la sociedad por su decadencia moral.",
        trailer: "https://youtu.be/xhzBmjdehPA?si=0xyRfln19bu9bHPd",
        year: "1995",
        director: "David Fincher"
    },
    {
        id: 84,
        title: "paddington 2", 
        category: ["Comedia", "Familia", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.4, 
        img: "https://play-lh.googleusercontent.com/SYQIY9b_piP5m81pbctoaf0-Kq8fNUaZCFnfBhw5xAY07wf0dfzLYL91B2spILovasI" ,
        description: "Paddington ya es un miembro amado de la comunidad de Windsor Gardens. Para el cumpleaños número 100 de su tía Lucy, encuentra un libro 'pop-up' único de Londres en la tienda de antigüedades del Sr. Gruber. Mientras ahorra trabajando en empleos divertidos (y desastrosos), el libro es robado por Phoenix Buchanan (Hugh Grant), un actor egocéntrico y maestro del disfraz. Paddington es injustamente encarcelado y, mientras su familia busca al verdadero culpable, él termina transformando la prisión y a sus rudos compañeros con su inquebrantable cortesía y sus sándwiches de mermelada.",
        trailer: "https://youtu.be/yiXpBIeS2x8?si=OcMnMQo55o9Ic6G8",
        year: "2017",
        director: "Paul King"
    },
    {
        id: 85,
        title: "Mrs. Doubtfire", 
        category: ["Comedia", "Drama", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.4, 
        img: "https://play-lh.googleusercontent.com/nMbEfiECATfTEUBfEZdkBh4DkAsLFOT6TnxmPmsT1NtwmDJNxIuk_4lkizq6fR0oYuV-",
        description: "Daniel Hillard es un actor de doblaje talentoso pero irresponsable que pierde la custodia de sus tres hijos tras un divorcio difícil de su esposa Miranda. Desesperado por pasar tiempo con ellos, Daniel descubre que Miranda está buscando una niñera. Con la ayuda de su hermano maquillador, Daniel se somete a una transformación física total para convertirse en la Sra. Euphegenia Doubtfire, una estricta pero adorable ama de llaves escocesa. La situación se vuelve una carrera de obstáculos mientras Daniel intenta mantener su doble vida sin que su exesposa o sus hijos lo descubran.",
        trailer: "https://youtu.be/jDE6fj6-QeQ?si=iL3jwsX9vc612ucl",
        year: "1993",
        director: "Chris Columbus"
    },
    {
        id: 86,
        title: "LLuvia de Hamburguesas", 
        category: ["Comedia", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.8, 
        img: "https://play-lh.googleusercontent.com/rSOdArYGNXxvDyDhtFU6G0XhLU_hh3A9JrJGYv2K_4XkJyu_rT4Z69audTT8gpMeNwYG" ,
        description: "En la pequeña isla de Isla Bocado (Chewandswallow), donde la economía colapsó y todos están obligados a comer sardinas en todas sus formas, vive Flint Loco, un inventor incomprendido. Flint crea el FLDSMDFR (Flint Lockwood Diatonic Super Mutating Dynamic Food Replicator), una máquina que convierte el agua en comida. Tras un accidente, la máquina termina en la atmósfera y comienza a llover hamburguesas, pizza y helado. Pero cuando la avaricia del alcalde obliga a la máquina a trabajar de más, la comida empieza a mutar en tamaños catastróficos, amenazando con destruir el mundo bajo una tormenta de espaguetis y albóndigas gigantes.",
        trailer: "https://youtu.be/pUaKcFI4BZY?si=moY2c9WOOZ4_0Lju",
        year: "2009",
        director: "Phil Lord y Christopher Miller"
    },
    {
        id: 87,
        title: "School of Rock", 
        category: ["Comedia", "Musica", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.2, 
        img: "https://upload.wikimedia.org/wikipedia/en/thumb/1/11/School_of_Rock_Poster.jpg/250px-School_of_Rock_Poster.jpg" ,
        description: "Dewey Finn es un guitarrista con sueños de grandeza que acaba de ser expulsado de su banda y está a punto de ser desalojado por no pagar la renta. Desesperado, intercepta una llamada dirigida a su compañero de cuarto y se hace pasar por él para trabajar como maestro sustituto en una prestigiosa y estricta escuela primaria privada. Al descubrir el talento musical de sus alumnos, Dewey decide abandonar el plan de estudios tradicional y convierte a la clase en una banda de rock de alto nivel para competir en la 'Batalla de las Bandas' y ganar el premio en efectivo.",
        trailer: "https://youtu.be/TExoc0MG4I4?si=AeYoVHJwBBLCoU1t",
        year: "2009",
        director: "Phil Lord y Christopher Miller"
    },
    {
        id: 88,
        title: "Viernes de locos 1", 
        category: ["Comedia", "Sci-Fi", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.4, 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpl1tX_N1sMg3mG1odFCGvt6Snl3LkzQWBIJfn8Uzy7ytquLHm-YQ0XxtFB8oN2f_1jgUG9SHPDMSVIs_GK4H35TdXyN3Yqy7KUraFdw&s",
        description: "La doctora Tess Coleman (Jamie Lee Curtis) y su hija adolescente Anna (Lindsay Lohan) no se llevan nada bien: tienen gustos opuestos en música, ropa y, sobre todo, no se entienden la una a la otra. Tras una fuerte discusión en un restaurante chino, unas galletas de la fortuna mágicas hacen que despierten una en el cuerpo de la otra. Ahora, Tess debe sobrevivir a la secundaria y a los ensayos de la banda de rock de Anna, mientras que Anna debe lidiar con los pacientes de su madre y su inminente boda. Solo lograran regresar a la normalidad cuando comprendan realmente lo que significa estar en los zapatos de la otra.",
        trailer: "https://youtu.be/I5bQG2u3RwU?si=gcpwXtxpUAEWb3nz",
        year: "2003",
        director: "Mark Waters"
    },
    {
        id: 89,
        title: "La la land", 
        category: ["Romance", "Musica", "Pelicula"], 
        type: "Pelicula", 
        rating: 4.7, 
        img: "https://es.web.img3.acsta.net/pictures/16/11/30/17/44/581119.jpg" ,
        description: "En Los Ángeles, la ciudad donde todos buscan el éxito, se cruzan las vidas de Mia (Emma Stone), una aspirante a actriz que sirve café en un estudio de cine entre audiciones fallidas, y Sebastian (Ryan Gosling), un pianista de jazz purista que sueña con abrir su propio club. Ambos se enamoran mientras persiguen sus ambiciones, pero a medida que sus carreras comienzan a despegar, deben enfrentarse a una decisión difícil: ¿puede el amor sobrevivir cuando las metas personales los empujan en direcciones opuestas?",
        trailer: "https://youtu.be/lYidGPGXEDg?si=I_S5vl9uzoCJzkrf",
        year: "2016",
        director: "Damien Chazelle"
    },
    {
        id: 90,
        title: "Diario de una Pasion", 
        category: ["Romance", "Drama"], 
        type: "Pelicula", 
        rating: 4.7, 
        img: "https://m.media-amazon.com/images/M/MV5BM2RiMzcxYmYtNzQ3MC00NTQ4LWE0ZjktNGUwODI1MzhjNDNkXkEyXkFqcGc@._V1_.jpg" ,
        description: "La historia comienza en una residencia de ancianos, donde un hombre llamado Duke le lee a una mujer con demencia el contenido de un cuaderno viejo. La lectura nos transporta a los años 40, en Carolina del Sur, donde el joven obrero Noah Calhoun y la chica rica Allie Hamilton viven un apasionado romance de verano que es interrumpido por la diferencia de clases y la Segunda Guerra Mundial. Años después, tras cientos de cartas sin respuesta y vidas separadas, sus caminos vuelven a cruzarse, obligando a Allie a elegir entre su prometido perfecto y su primer amor inolvidable.",
        trailer: "https://youtu.be/fwlmQ3PCZ9g?si=S2cqoRz0OlXxfcaz",
        year: "2004",
        director: "Nick Cassavetes."
    }
    // Sigue Aqui con las Pelis no se te olvide yo del futuro
    // y todas deben tener comas al final excepto la ultima yo del futuro
];